name: Required Secret Scan (TruffleHog)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
